### ISSUE TITLE
Some projectiles collide on seemingly nothing

### ISSUE THREAD

**Issue by ldesgoui** [ldesgoui/tf2-comp-fixes#23]

**Comment by ldesgoui** [comment]
func_lod causes this, maps should just not use it

**Comment by bakugo** [comment]
@ldesgoui 

It's not just caused by func_lod, other entities like func_brush and prop_dynamic also cause it to happen to the Wrap Assassin. The control point on koth_nucleus is the most obvious spot where this happens.

Either way I made a  fix for this after the source leak, if you're still interested in adding it to your plugin.

[projectile_collide_fix.zip](https://github.com/ldesgoui/tf2-comp-fixes/files/4663446/projectile_collide_fix.zip)

**Comment by ldesgoui** [comment]
Nice work, will check it out whenever I have some free time

**Comment by bakugo** [comment]
I have released this as a standalone plugin, for anyone interested:
https://forums.alliedmods.net/showthread.php?t=325411

**Comment by ldesgoui** [comment]
This should be fixed in the base game.
